export interface ReceiptData {
  receiptNumber: string;
  contractId: number;
  projectTitle: string;
  actorName: string;
  producerName: string;
  paymentAmount: string;
  paymentDate: Date;
  paymentMethod: string;
}

/**
 * Generate receipt text content
 */
export function generateReceiptText(data: ReceiptData): string {
  const formattedDate = data.paymentDate.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  
  const formattedAmount = `$${parseFloat(data.paymentAmount).toFixed(2)} USD`;
  
  return `
════════════════════════════════════════════════════════
                    PAYMENT RECEIPT
                      FilmContract
        Transparent contracts for film professionals
════════════════════════════════════════════════════════

Receipt #${data.receiptNumber}
Date: ${formattedDate}

────────────────────────────────────────────────────────
PAYMENT DETAILS
────────────────────────────────────────────────────────

Amount Paid:        ${formattedAmount}
Payment Method:     ${data.paymentMethod}
Payment Date:       ${formattedDate}

────────────────────────────────────────────────────────
CONTRACT INFORMATION
────────────────────────────────────────────────────────

Contract ID:        #${data.contractId}
Project Title:      ${data.projectTitle}
Producer:           ${data.producerName}
Actor:              ${data.actorName}

────────────────────────────────────────────────────────

This receipt confirms payment received for the above
contract. For questions or concerns, please contact
the producer directly.

Generated by FilmContract
${new Date().toLocaleString("en-US")}

════════════════════════════════════════════════════════
`;
}

/**
 * Download receipt as a text file
 * (Works on web, on mobile it will trigger a share dialog)
 */
export function downloadReceiptPDF(data: ReceiptData, filename?: string): void {
  const receiptText = generateReceiptText(data);
  const defaultFilename = `FilmContract_Receipt_${data.receiptNumber}.txt`;
  const finalFilename = filename || defaultFilename;
  
  // Create a blob from the text
  const blob = new Blob([receiptText], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  
  // Create a temporary link and trigger download
  const link = document.createElement("a");
  link.href = url;
  link.download = finalFilename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  // Clean up the URL
  URL.revokeObjectURL(url);
}
